### ISSUE TITLE
105.CSS filter

### ISSUE THREAD

**Issue by neptoo** [neptoo/one-step#105]
### 查看原文

[b站全灰，原来仅需一行css代码——css 滤镜](https://juejin.im/post/5df3a049f265da33f8652882)

### filter滤镜

```javascript
    const url = "https://www.baidu.com/img/baidu_resultlogo@2.png";
    let html = "";
    [
      {
        name: "灰度100%",
        style: "grayscale(100%)"
      },
      {
        name: "模糊5px",
        style: "blur(5px)"
      },
      {
        name: "3倍亮度",
        style: "brightness(300%)"
      },
      {
        name: "200%对比度",
        style: "contrast(200%)"
      },
      {
        name: "200%饱和度",
        style: "saturate(200%)"
      },
      {
        name: "色相旋转180度",
        style: "hue-rotate(180deg)"
      },
      {
        name: "100%反色",
        style: "invert(100%)"
      },
      {
        name: "50%透明度",
        style: "opacity(50%)"
      },
      {
        name: "阴影",
        style: "drop-shadow(10px 5px 5px #f00)"
      },
      {
        name: "100%透明度",
        style: "opacity(100%)"
      },
      {
        name: "褐色程度70%",
        style: "sepia(70%)"
      }
    ].forEach(({ name, style }) => {
      html += `<div>${name}-${style}: <img src=${url} style="filter: ${style}" /></div><br />`;
    });
    document.body.innerHTML = html;
```

![filter属性效果预览](https://user-gold-cdn.xitu.io/2019/12/13/16effd1a47d526f7?imageView2/0/w/1280/h/960/format/webp/ignore-error/1)

### 模糊阴影

![模糊彩色阴影](https://user-gold-cdn.xitu.io/2019/12/14/16f0007e34221e5f?imageView2/0/w/1280/h/960/format/webp/ignore-error/1)

```css
.shadow, .shadow::before {
  width: 500px;
  height: 400px;
  background: url("http://img2.imgtn.bdimg.com/it/u=1737072847,1699534261&fm=26&gp=0.jpgg") no-repeat;
  background-size: cover;
}
.shadow {
  position: relative;
}
.shadow::before {
  content: "";
  display: block;
  position: absolute;
  filter: blur(20px);
  z-index: -1;
  top: 20px;
  left: 20px;
}
```
