### ISSUE TITLE
106.CSS布局技巧(2)：文本省略、细边框、倒序文本

### ISSUE THREAD

**Issue by neptoo** [neptoo/one-step#106]
> 查看原文: [灵活运用CSS开发技巧](https://juejin.im/post/5d4d0ec651882549594e7293)
>
> 作者：[JowayYoung](https://juejin.im/user/584ec3a661ff4b006cd6383e)

### 文本溢出

```css
/* 单行文本溢出 */
.sl-ellipsis{
  over-flow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  /*nowrap：连续的空白符会被合并。但文本内的换行无效。*/
}
```

```scss
/*多行文本溢出*/
.ml-ellipsis{
  display: -webkit-box;
  overflow: hidden;
  text-overflow: ellipsis;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical; /* */
}

/*多行文本溢出-伪元素模糊末尾*/
.ml-ellipsis2{
  over-flow: hidden;
  max-height: 90px;
  position: relative;
  &::after{
    position: absolute;
    right: 0;
    bottom: 0;
    padding-left: 40px;
    background: linear-gradient(to right, transparent, #fff 50%);
    content: '...';
  }
}
```

![文本省略](https://yangzw.vip/static/article/css-skill/%E4%BD%BF%E7%94%A8text-overflow%E6%8E%A7%E5%88%B6%E6%96%87%E6%9C%AC%E6%BA%A2%E5%87%BA.png)

### 1px边框

```scss
/* 分辨率比较低的屏幕下显示1px的边框会显得模糊，通过transform模拟细腻的1px边框 */
.normal{ border: 1px solid #f66; }

.thin{
  position: relative;
  &::after{
    position: absolute;
    top: 0;
    left: 0;
    border: 1px solid #f66;
    width: 200%;
    height: 200%;
    content: "";
    /* transform-origin改变元素变形的原点 */
    transform: scale(.5);
    transform-origin: top left;
  }
}
```

![细边框](https://yangzw.vip/static/article/css-skill/%E4%BD%BF%E7%94%A8transform%E6%8F%8F%E7%BB%981px%E8%BE%B9%E6%A1%86.png)

### 倒序文本

```scss
.reverse-text{
  font-size: 30px;
  color: #f66;
  letter-spacing: -60px;
  // letter-spacing最少是font-size的2倍
}
```

![反序](https://yangzw.vip/static/article/css-skill/%E4%BD%BF%E7%94%A8letter-spacing%E6%8E%92%E7%89%88%E5%80%92%E5%BA%8F%E6%96%87%E6%9C%AC.png)

### 推荐阅读

[white-space](https://developer.mozilla.org/zh-CN/docs/Web/CSS/white-space)

[transform-origin](https://developer.mozilla.org/zh-CN/docs/Web/CSS/transform-origin)
