### ISSUE TITLE
109.CSS左边固定右边自适应布局

### ISSUE THREAD

**Issue by neptoo** [neptoo/one-step#109]
> 查看原文：
>
> [常见的布局类问题及面经](https://juejin.im/post/5a1e2f246fb9a045186a7db2)
>
> [CSS布局解决方案（终结版）](https://segmentfault.com/a/1190000013565024?utm_source=channel-hottest#item-2)

#### 1.flex

```css
.container{
  display: flex;
}
.left{
  width: 100px;
}
.right{
  flex: 1;
}
```

#### 2.float+overflow

```css
.left{
  float: left;
  background: red;
  width: 200px;
}
.right{
  overflow: auto;
  background: blue;
}
```

**当我们给右侧的元素单独创建一个BFC时，它将不会紧贴在包含块的左边框，而是紧贴在左元素的右边框。**

#### 3.float+margin-left

```css
.left{
  float: left;
  width: 200px;
}
.right{
  margin-left: 200px;
}
```

#### 4.float+margin-left+父BFC

```html
<div class="left"></div>
<div class="right-fix">
  <div class="right"></div>
</div>
```

```css
.left{
  float: left;
  width: 100px;
  position: relative;
}
.right-fix{
  float: right;
  width: 100%;
  margin-left: -100px;
}
.right{
  margin-left: 100px;
}
```

#### 5.浮动+calc()

```css
.left, .right{
  float: left;
}
.right{
  width: calc(100vw - 200px);
}
```
