### ISSUE TITLE
12.前端网页样式

### ISSUE THREAD

**Issue by neptoo** [neptoo/one-step#12]
### 移动端

**line-height**

```css
.demo{
    height:16px;
    line-height:14px;
    font-size:9px;
    border:1px solid #ff6815;
}
/* 稍微大一点的高度，最好把line-height设置为高度+1px。*/
```

**多行省略**

```css
/* 列表标题行数限制*/
.demo{
    display: -webkit-box;    //1.设置display类型为-webkit-box
    font-size: 14px;
    line-height: 18px;
    overflow: hidden;        //2.设置元素超出隐藏
    text-overflow: ellipsis; //3.设置超出样式为省略号
    -webkit-line-clamp: 2;   //4.设置2行应用省略
    -webkit-box-orient: vertical;
}
```

### 网页

**内容**

```css
body {
  margin: 0 auto;
  max-width: 50em;
}
```

**字体**

```css
body {
  font-family: "Helvetica", "Arial", sans-serif;
}
```

**间距**

```css
body {
  line-height: 1.5;
  padding: 4em 1em;
}

h2 {
  margin-top: 1em;
  padding-top: 1em;
}
```

**字体颜色**

```css
body {
  color: #555;
}
h1,h2,strong {
  color: #333;
}
```

自定义字体 [Adobe Fonts](https://fonts.adobe.com/) [谷歌字体库](https://fonts.google.com/)

```css
@import url('https://fonts.googleapis.com/css?family=Work+Sans&display=swap');
body { font-family: 'Work Sans', sans-serif;}
```

### 参考文章

[4分钟网页设计](https://jgthms.com/web-design-in-4-minutes/#share)
