### ISSUE TITLE
37.水平垂直居中

### ISSUE THREAD

**Issue by neptoo** [neptoo/one-step#37]
### 水平居中

1. **行内元素**  `text-align:center`

2. **块级元素** `margin:0 auto`

3. **flex **

```javascript
.son{
    display: flex;
    justify-content: center;
}
```

4. **绝对定位**

```javascript
.son{
    position:absolute;
    width:固定;
    left:50%;
    margin-left:-0.5宽度;
}
```

5. **transform**

```javascript
.son{
    position:absolute;
      left:50%;
      transform:translate(-50%,0);
}
```

6. 子元素包含 float:left 属性, 则可让父元素宽度设置为**fit-content**, 并且配合margin, 设置:

```javascript
.parent{
    width: -moz-fit-content;
    width: -webkit-fit-content;
    width:fit-content;
    margin:0 auto;
}
```

#### 单行文本

若元素是单行文本, 则可设置 `line-height` 等于父元素高度

#### 行内块级元素

若元素是行内块级元素, 基本思想是使用`display: inline-block, vertical-align: middle`和一个伪元素让内容块处于容器中央.

```javascript
.parent::after, .son{
    display:inline-block;
    vertical-align:middle;
}
.parent::after{
    content:'';
    height:100%;
}
```

#### 图片

```css
#parent{
    height: 150px;
    line-height: 150px;
    font-size: 0;
}
img#son{vertical-align: middle;} /*默认是基线对齐，改为middle*/
```

#### 元素高度不定

1. vertical-align:middle;

   设置父元素display:table, 子元素 display:table-cell;vertical-align:middle;

2. flex

```css
.parent {
  display: flex;
  align-items: center;
}
```

3. transform

```css
.son{
    position:absolute;
    top:50%;
    -webkit-transform: translate(-50%,-50%);  
    -ms-transform: translate(-50%,-50%);
    transform: translate(-50%,-50%);
}
```

#### 元素高度固定

```javascript
.son{
    position:absolute;
    top:50%;
    height:固定;
    margin-top:-0.5高度;
}
```

### 参考文章

[16种方法实现水平居中垂直居中](https://juejin.im/post/58f818bbb123db006233ab2a)、

[干货!各种常见布局实现+知名网站实例分析](https://juejin.im/post/5aa252ac518825558001d5de)
