### ISSUE TITLE
40.CSS3相关知识点

### ISSUE THREAD

**Issue by neptoo** [neptoo/one-step#40]
#### 区别

float、margin collapse 等是为了满足段落排版等需求；position 更接近”布局“属性，但无法实现元素关联约束。

布局一般应该使用 column layout、flex box、grid layout 等来解决。

position 是定位，float 让元素脱离文档流，不占据文档流空间。（position的absolute和fixed同样不占）

> 当一个元素浮动之后，它会被移出正常的文档流，然后向左或者向右平移，一直平移直到碰到了所处的容器的边框，或者碰到另外一个浮动的元素。

#### 同时使用

float浮动与position同时使用并不会冲突，前者是使元素脱离标准流，浮动在文档流上；而后者是使元素相对自身的移动定位，虽浮动但占据原有位置。当两者同时使用时，不会发生冲突，反而使元素同时具有两者特性。

### 2、position的static、relative、absolute、fixed它们的区别？

- `absolute`：生成绝对定位的元素，相对于 `static` 定位以外的第一个父元素进行定位
- `fixed`：相对于浏览器窗口进行定位
- `relative`：生成相对定位的元素，相对于其正常位置进行定位
- `static` 默认值。没有定位，元素出现在正常的流中
- `inherit` 规定从父元素继承 `position` 属性的值

### 3、纯CSS样式写三角形icon

```css
.div-angles{  /*顶角朝上*/
	 width: 0;
	 height: 0;
	 border-style: solid;
	 border-width:30px;
	 width:0px;
	 height:0px;
	 border-color: transparent transparent #06c transparent;
}
```

### 4、before、after伪元素

- 单冒号(:)用于CSS3伪类，双冒号(::)用于CSS3伪元素。
- 想让插入的内容出现在其它内容前，使用::before，之后则使用::after

### 5、表单自动填充的颜色

```css
input:-webkit-autofill, textarea:-webkit-autofill, select:-webkit-autofill {
  background-color: #fff;//设置成元素原本的颜色
  background-image: none;
  color: rgb(0, 0, 0);
}
//方法2：由掘金大神 (licongwen )补充
input:-webkit-autofill {
    -webkit-box-shadow: 0px 0 3px 100px #ccc inset; //背景色
}
```

### 参考文章

[那些年你踩过的坑，都在这里了～| 掘金技术征文](https://juejin.im/post/5ba6e77e6fb9a05d0b14359b#heading-7)

[float与position同时使用-CSDN](https://blog.csdn.net/qq_27346075/article/details/82288242)

[在 CSS 中，用 float 和 position 的区别是什么？-知乎](https://www.zhihu.com/question/19588854)
