### ISSUE TITLE
41.移动端适配

### ISSUE THREAD

**Issue by neptoo** [neptoo/one-step#41]
### 基本概念

英寸，是指屏幕对角线的物理大小。

图片分辨率，是指图片含有的`像素数`。

在`iOS`、`Android`和`React Native`开发中样式单位其实都使用的是设备独立像素。

> 为了适配所有机型，我们在写样式时需要把物理像素转换为设备独立像素：例如：如果给定一个元素的高度为`200px`(这里的`px`指物理像素，非`CSS`像素)，`iphone6`的设备像素比为`2`，我们给定的`height`应为`200px/2=100dp`。

### 1.如何画一条 0.5px 的线?

`Chrome`把 0.5px 四舍五入变成了 1px，并且`Chrome`会把小于 0.5px 的当成 0，而`Firefox`会把不小于 0.55px 当成 1px，`Safari`是把不小于 0.75px 当成 1px，进一步在手机上观察 IOS 的 Chrome 会画出 0.5px 的边，而安卓(5.0)原生浏览器是不行的。所以直接设置 0.5px 不同浏览器的差异比较大。

解决方法: 使用缩放 `transform : scaleY(0.5)`

```css
.hr-half {
   height: 1px;
   transform: scaleY(0.5);
}
```

### 2. 1px问题

**2.1 border-image**

```css
       .border_1px{
          border-bottom: 1px solid #000;
        }
        @media only screen and (-webkit-min-device-pixel-ratio:2){
            .border_1px{
                border-bottom: none;
                border-width: 0 0 1px 0;
                border-image: url(../img/1pxline.png) 0 0 2 0 stretch;
            }
        }
```

**2.2 伪类+transform**

```css
       .border_1px:before{
          content: '';
          position: absolute;
          top: 0;
          height: 1px;
          width: 100%;
          background-color: #000;
          transform-origin: 50% 0%;
        }
        @media only screen and (-webkit-min-device-pixel-ratio:2){
            .border_1px:before{
                transform: scaleY(0.5);
            }
        }
        @media only screen and (-webkit-min-device-pixel-ratio:3){
            .border_1px:before{
                transform: scaleY(0.33);
            }
        }
```

**2.3 SVG+PostCSS**

### 3.vh、vw方案

`vh、vw`方案即将视觉视口宽度 `window.innerWidth`和视觉视口高度 `window.innerHeight` 等分为 100 份。

缺点：`px`转换成`vw`不一定能完全整除，因此有一定的像素差。比如当容器使用`vw`，`margin`采用`px`时，很容易造成整体宽度超过`100vw`，从而影响布局效果。当然我们也是可以避免的，例如使用`padding`代替`margin`，结合`calc()`函数使用等。

### 4.横屏

**4.1 JS**

```javascript
window.addEventListener("resize", ()=>{
    if (window.orientation === 180 || window.orientation === 0) { 
      // 正常方向或屏幕旋转180度
        console.log('竖屏');
    };
    if (window.orientation === 90 || window.orientation === -90 ){ 
       // 屏幕顺时钟旋转90度或屏幕逆时针旋转90度
        console.log('横屏');
    }  
}); 
```

**4.2 CSS**

```css
@media screen and (orientation: portrait) {
  /*竖屏...*/
} 
@media screen and (orientation: landscape) {
  /*横屏...*/
}
```

### 强烈推荐

[关于移动端适配，你必须要知道的-ConardLi](https://juejin.im/post/5cddf289f265da038f77696c)
