### ISSUE TITLE
42. CSS动画

### ISSUE THREAD

**Issue by neptoo** [neptoo/one-step#42]
题目：一个小球向右匀速200px，往回，再往右，停在200px的位置。

![滚动的小球](https://user-gold-cdn.xitu.io/2019/5/16/16abfbc339e758eb?imageslim)

```css
div {
  width: 30px;
  height: 30px;
  border-radius: 50%;
  background: #0ff;
  animation: move 2s linear 3 alternate both;
  /* alternate 偶数次2，4是反向回去;*/
}
@keyframes move {
  0% {
    transform: translate(0, 0);
  }
  100% {
    transform: translate(200px, 0);
  }
}
```

`animation-fill-mode` 填充模式，除了默认值 `none` 外，还有另外 3 个值：

- forwards，表示，动画完成后，元素状态保持为最后一帧的状态。
- backwards，表示，有动画延迟时，动画开始前，元素状态保持为第一帧的状态。
- both，表示上述二者效果都有。

> 设置动画延迟 `1s` 后执行，且填充模式为 `backwards` 时，可以看到动画在开始前是处于 `100px` 处，动画结束后回到 `0px` 处。

 `animation-delay` 设置延迟时间。不为大家注意的是，延迟可以为负数。负延迟表示动画仿佛开始前就已经运行过了那么长时间。

拿进度条为例子，原动画用了 `2s` 是从 `0%` 加载到 `100%` 的。如果设置延迟为 `-1s`。这动画会从 `50%` 加载到 `100%`。仿佛已经运行了 `1s` 一样。（已经到了50%）

[原文链接](https://juejin.im/post/5cdd178ee51d456e811d279b)
