### ISSUE TITLE
62.点击改变样式

### ISSUE THREAD

**Issue by neptoo** [neptoo/one-step#62]
**题目：实现效果，点击容器内的图标，图标边框变成border 1px solid red，点击空白处重置。**

思路：利用 `event.target` 判断是否为元素本身，因为是容器内，所以禁止冒泡。

```html
<div id="app">
  <span class="icon"></span>
</div>
```

```css
#app{
  min-width: 100vw;
  min-height: 100vh;
}
#app .icon{
  display: inline-block;
  cursor: pointer;
}
```

```javascript
const app = document.querySelector("#app");
const icon = document.querySelector(".icon");
app.addEventListener("click", e => {
  if(e.target === icon){ return ;}
  icon.style.border = "none";
});
icon.addEventListener("click", e => {
  e.stopPropagation;
  icon.style.border = "1px solid red";
});
```
