### ISSUE TITLE
63.CSS阴影动画优化

### ISSUE THREAD

**Issue by neptoo** [neptoo/one-step#63]
### 问题情景

一个盒子

```css
div{
  width: 100px;
  height: 100px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
}
```

希望hover时，发生如下变化：`box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);` >> `box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);`。

```css
div:hover{
  width: 100px;
  height: 100px;
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);
}
```

过渡动画发生在两个阴影重绘期间，由于浏览器重绘，性能有所影响，卡顿。

### 伪元素优化

思路：使用伪元素，大小与 div 一致，给元素添加好最终的阴影状态，但元素透明度为0。

```css
div{
  width: 100px;
  height: 100px;
  position: relative;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
}
div::before{
  position: absolute;
  content: "";
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);
  opacity: 0;
}
```

然后在 hover 的时候将透明度改为1。

```css
div:hover::before{
  opacity: 1;
}
```

缺陷：最终效果是两个阴影叠加。

### 进一步优化

思路：再添加一个 `::after` 伪元素，设置为初始状态并且透明度为1， `::before` 伪元素，设置为最终状态并且透明度为0。

```css
div {
    position: relative;
    width: 100px;
    height: 100px;
}

div::before {
    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);
    opacity: 0;
}

div::after {
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
}
```

在 hover 的时候，伪元素一隐一显，最终只有一个阴影效果。

```css
div:hover::before {
    opacity: 1;
}

div:hover::after {
    opacity: 0;
}
```

### 阅读原文

[CSS 阴影动画优化技巧一则—chokcoco](https://juejin.im/post/5dba4275f265da4d307f1058)

[How to animate box-shadow with silky smooth performance](https://tobiasahlin.com/blog/how-to-animate-box-shadow/)
