### ISSUE TITLE
72.CSS知识点

### ISSUE THREAD

**Issue by neptoo** [neptoo/one-step#72]
#### 1.文本缩进

块级用 `text-indent`，内联用 `margin-left`

```css
div1{
  display: block;
  text-indent: 85;
}
div2{
  display: inline;
  margin-left: 85;
}
```

#### 2.表格样式

```html
<style>
table,tr,th,td {
  border: 1px solid #d6d6d6;
}

table {
  width: 100%;
  color: #555;
  font-size: 14px;
  border-collapse: collapse;
  /*  collapse 相邻的单元格共用同一条边框  */
  table-layout: fixed;
  /* auto 大多数浏览器采用自动表格布局算法对表格布局。表格及单元格的宽度取决于其包含的内容。
     fixed 表格和列的宽度通过表格的宽度来设置，某一列的宽度仅由该列首行的单元格决定。 */
}

th,td {
  padding: 6px 12px;
}

tr:nth-child(odd) {
  background-color: aliceblue;
}

tr:hover {
  background-color: aquamarine;
}

tr {
  transition: background-color 1s;
}
</style>

<table>
  <colgroup>
    <col span="3">
    </col>
    <col style="width:260px;">
    </col>
  </colgroup>
  <tr>
    <th>等级</th>
    <th>掘力值</th>
    <th>身份</th>
    <th>权限</th>
  </tr>
  <tr>
    <td>Lv3</td>
    <td>1000</td>
    <td></td>
    <td>开发中</td>
  </tr>
  <tr>
    <td>Lv4</td>
    <td>5000</td>
    <td>掘金优秀作者</td>
    <td>自动推荐至首页，专栏添加 2 个标签</td>
  </tr>
  <tr>
    <td>Lv5</td>
    <td>10000</td>
    <td></td>
    <td>小册写作权限</td>
  </tr>
  <tr>
    <td>Lv6</td>
    <td>20000</td>
    <td>掘金共建者</td>
    <td>提交、维护标签，掘金共建者证书</td>
  </tr>
</table>
```

#### 3.滚动条样式优化

> `::-webkit-scrollbar` 仅仅在支持[WebKit](https://webkit.org/)的浏览器 (例如, 谷歌Chrome, 苹果Safari)可以使用.

```css
::-webkit-scrollbar-thumb{
  /* 滚动条上的滚动滑块 */
  background: linear-gradient(orange, red);
  border-radius: 10px;
}
::-webkit-scrollbar{
  width: 10px;
}
::-webkit-scrollbar-track{
  /* 滚动条轨道 */
  background: pink;
}
```

#### 查看原文

[你未必知道的CSS知识点（第二季）](https://juejin.im/post/5d9ec8b0518825651b1dffa3)
