### ISSUE TITLE
73.CSS 知识点（2）

### ISSUE THREAD

**Issue by neptoo** [neptoo/one-step#73]
#### 1.文本对齐justify

```css
.main{
  display: flex;
  justify-content: between;
}
```

使用文本对齐属性值justify，实现类似弹性布局的space-between效果。

```css
.main{
  text-align: justify;
}
.main::after{  /* ::伪元素 */
  content: "";
  display: inline-block;
  width: 100%;
}
```

```css
.main{
  text-align-last: justify;
}
```

#### 2.自定义选区样式

```css
::selection{
  color: white;
  background: purple;
  /* 所选择的文本样式 */
}
h1::selection{
  background: #ff3;
}
```

#### 3. :target伪类选择器

:target 代表一个唯一的页面元素(目标元素)，其`id` 与当前URL片段匹配 .

```html
<style>
  div{ transition: flex 1s; }
  div:target{
    flex: 1;
    background: purple;
  }
</style>
<div>
  <a href="#1">1</a>
  <a href="#2">2</a>
  <a href="#3">3</a>
</div>
<main>
  <div id="1"></div>
  <div id="2"></div>
  <div id="3"></div>
</main>
```

#### 4.⚪变🌈

```css
div {
  width: 200px;
  height: 200px;
  border-radius: 50%;
  /* background: tan; */
}
div {
  box-shadow: 0 0 0 5px inset red, 0 0 0 10px inset orange,
    0 0 0 15px inset yellow, 0 0 0 20px inset lime, 0 0 0 25px inset aqua,
    0 0 0 30px inset blue, 0 0 0 35px inset magenta;
  clip-path: polygon(0 0, 100% 0, 100% 50%, 0 50%);
}
```

[CodePen](https://codepen.io/neptoo/full/Vwwdoyz)

#### 查看原文

[你未必知道的CSS知识点（第二季）](https://juejin.im/post/5d9ec8b0518825651b1dffa3)
