### ISSUE TITLE
74.CSS实现人脸扫描效果

### ISSUE THREAD

**Issue by neptoo** [neptoo/one-step#74]
#### 人脸扫描图

CSS实现人脸扫描效果：

```css
div{
	width: 160px;
	height: 200px;
	background: linear-gradient(#03A9F4,#03A9F4), 
  linear-gradient(90deg, #ffffff33 1px,transparent 0,transparent 19px),
  linear-gradient(#ffffff33 1px,transparent 0,transparent 19px),
  linear-gradient(transparent, #2196f387);
	background-size:100% 1.5%, 10% 100%,100% 10%, 100% 100%;
	background-repeat: no-repeat,repeat,repeat,no-repeat;
	background-position: 0 0,0 0, 0 0, 0 0;
	clip-path: polygon(0% 0%, 100% 0%, 100% 1.5%, 0% 1.5%);
	animation: move 2s infinite linear;
}
@keyframes move{
	to{
		background-position: 0 100%,0 0, 0 0, 0 0;
		clip-path: polygon(0% 0%, 100% 0%, 100% 100%, 0% 100%);
	}
```

```html
<img src="https://i.loli.net/2019/11/11/mYeFVhPf7JWvkE5.jpg" height="200" style="position: absolute;"/>
<div></div>
```

[CodePen](https://codepen.io/neptoo/full/eYYjyvw)

#### 查看原文

[你未必知道的CSS知识点（第二季）](https://juejin.im/post/5d9ec8b0518825651b1dffa3)
