### ISSUE TITLE
86.橡皮筋特效

### ISSUE THREAD

**Issue by neptoo** [neptoo/one-step#86]
### Scroll bouncing

弹簧特效（同样被叫做滑动橡皮筋特效或弹性滚动），经常发生于下面的场景：

当滚动到页面或者html元素的最上或者最下部的时候，在页面或者元素回到顶部/底部之前(即你松开手指或者鼠标之前)，会短暂的看到空白区域的出现。

假如入我们有下面这个页面，底部有一个固定且不能移动的footer，同时页面其他内容可以滚动。如果我们使用mac上的 chrome 或 firefox 时，当用触摸板 scroll 到最下部时，事情就有点不一样了。

![scroll-bounce](https://user-gold-cdn.xitu.io/2018/8/20/16557cd22c2b7ef4?imageslim)

页面结构如下

```html
<html>
  <body>
    <div class="body-container">
      <div class="color-picker-main-container"> 
      </div>
    </div>
    <footer>
    </footer>
</body>    
```

### CSS解决方案

```css
html {
  width: 100%;
  height: 100%;
  overflow: hidden;
  position: relative;
}

body {
  width: 100%;
  margin: 0;
  font-family: sans-serif;
  height: 100%;
  overflow: hidden;
}

.body-container {
  /* content的高度就是100%减去footer的高度 */
  height: calc(100% - 100px);
  overflow: auto;
}

.color-picker-main-container {
  width: 100%;
  font-size: 22px;
  padding-bottom: 10px;
}

footer {
  position: absolute;
  /* 使用absolute来定位footer，然后html相对定位height100%，以便footer始终在下方固定 */
  bottom: 0;
  height: 100px;
  width: 100%;
}
```

缺陷：因为我们设置滑动容器的高度为它本身的100%，这样就阻碍了ios上的momentum-based scrolling，
这里的momentum-based scrolling，简称为阻尼滑动吧。简单而言就是移动设备上增加的一种旨在提升页面滑动性能的功能，比较明显的体现就是当你的手指轻触触碰设备表面时，页面自身开始滑动，当手指停止滑动之后页面还会顺势滑动一会。

### javascript解决方案

一种避免滑动弹簧的方式是阻止window或者document的touchmove或touchstart事件。思路是阻止外层window的tocuch事件，只允许content部分的touch。代码如下：

```js
// Prevents window from moving on touch on newer browsers.
window.addEventListener("touchmove", function(event) {
    event.preventDefault();
},{ passive: false });
```

> 工具库：另外可以使用iNoBounce来帮助自己，该库目的就是解决ios上web应用滑动时的弹簧效应。需要提一下的时，使用该库解决上面问题时要加上-webkit-overflow-scrolling。

CSS 属性`overscroll-behavior`，该属性CSS属性在2017年12月和2018年3月分别在Chrome 63、Firefox 59中实现。根据mdn的定义：允许你控制浏览器的滑动溢出的行为--当到达滚动区域的边边界时会发生的行为。这就是最后的一种方案。
需要做的仅仅是在body设置overscroll-behavior:none,并设置footer为fixed，相比于没有foter，整个页面应用momentum-based scrolling是可以接受的。 更加客观的是Edge正在开发中，未来可期。

### 阅读原文

[【译】谈橡皮筋特效的解决方案](https://juejin.im/post/5b7ad44c518825430c7a5f9f)
